
services:
  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    build: .docker/php
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www:cached
    networks:
      - app-network

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refactorian
      MYSQL_USER: refactorian
      MYSQL_PASSWORD: refactorian
    networks:
      - app-network

  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db
    volumes:
      - .docker/phpmyadmin/sessions:/sessions
    networks:
      - app-network

  ####################################################################################################
  # Adminer
  ####################################################################################################
  adminer:
    image: adminer
    ports:
      - "8822:8080"
    depends_on:
      - db
    networks:
      - app-network

  ####################################################################################################
  # Mailpit
  ####################################################################################################
  mail:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network

  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
